export const popups = [
  {
    "State": "Alabama",
    "Index": 1,
    "Lat": 32.31823,
    "Long": -86.902298,
    "ProjectTotal": 2,
    "BridgeDeckArea": 0,
    "PavementDistance": 4,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 0,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Alaska",
    "Index": 2,
    "Lat": 66.160507,
    "Long": -153.36914,
    "ProjectTotal": 4,
    "BridgeDeckArea": 335000,
    "PavementDistance": 540,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Arizona",
    "Index": 3,
    "Lat": 34.048927,
    "Long": -111.09374,
    "ProjectTotal": 6,
    "BridgeDeckArea": 2149078,
    "PavementDistance": 90,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Arkansas",
    "Index": 4,
    "Lat": 34.799999,
    "Long": -92.199997,
    "ProjectTotal": 6,
    "BridgeDeckArea": 354700,
    "PavementDistance": 50,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "California",
    "Index": 5,
    "Lat": 36.778259,
    "Long": -119.41793,
    "ProjectTotal": 28,
    "BridgeDeckArea": 4392370,
    "PavementDistance": 794,
    "PavementStructureEvaluation": 18,
    "BridgeDeckScanning": 6,
    "OtherProjects": 2,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 2,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Colorado",
    "Index": 6,
    "Lat": 39.113014,
    "Long": -105.35889,
    "ProjectTotal": 8,
    "BridgeDeckArea": 219386,
    "PavementDistance": 1260,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 2,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Connecticut",
    "Index": 7,
    "Lat": 41.599998,
    "Long": -72.699997,
    "ProjectTotal": 60,
    "BridgeDeckArea": 7073696,
    "PavementDistance": 600,
    "PavementStructureEvaluation": 20,
    "BridgeDeckScanning": 38,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 2,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Delaware",
    "Index": 8,
    "Lat": 39,
    "Long": -75.5,
    "ProjectTotal": 12,
    "BridgeDeckArea": 4152930,
    "PavementDistance": 0,
    "PavementStructureEvaluation": 0,
    "BridgeDeckScanning": 10,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 2,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Florida",
    "Index": 9,
    "Lat": 27.994402,
    "Long": -81.760254,
    "ProjectTotal": 10,
    "BridgeDeckArea": 622844,
    "PavementDistance": 264,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 2,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Georgia",
    "Index": 10,
    "Lat": 33.247875,
    "Long": -83.441162,
    "ProjectTotal": 56,
    "BridgeDeckArea": 50640,
    "PavementDistance": 2352,
    "PavementStructureEvaluation": 48,
    "BridgeDeckScanning": 8,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Hawaii",
    "Index": 11,
    "Lat": 19.741755,
    "Long": -155.84444,
    "ProjectTotal": 4,
    "BridgeDeckArea": 2779776,
    "PavementDistance": 22,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Idaho",
    "Index": 12,
    "Lat": 44.068203,
    "Long": -114.74204,
    "ProjectTotal": 62,
    "BridgeDeckArea": 2938058,
    "PavementDistance": 2758,
    "PavementStructureEvaluation": 32,
    "BridgeDeckScanning": 28,
    "OtherProjects": 2,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Illinois",
    "Index": 13,
    "Lat": 40,
    "Long": -89,
    "ProjectTotal": 46,
    "BridgeDeckArea": 6194354,
    "PavementDistance": 764,
    "PavementStructureEvaluation": 6,
    "BridgeDeckScanning": 38,
    "OtherProjects": 2,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Indiana",
    "Index": 14,
    "Lat": 40.273502,
    "Long": -86.126976,
    "ProjectTotal": 14,
    "BridgeDeckArea": 2037512,
    "PavementDistance": 648,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 10,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Iowa",
    "Index": 15,
    "Lat": 42.032974,
    "Long": -93.581543,
    "ProjectTotal": 6,
    "BridgeDeckArea": 200576,
    "PavementDistance": 10,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Kansas",
    "Index": 16,
    "Lat": 38.5,
    "Long": -98,
    "ProjectTotal": 8,
    "BridgeDeckArea": 0,
    "PavementDistance": 122,
    "PavementStructureEvaluation": 8,
    "BridgeDeckScanning": 0,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Kentucky",
    "Index": 17,
    "Lat": 37.839333,
    "Long": -84.27002,
    "ProjectTotal": 6,
    "BridgeDeckArea": 0,
    "PavementDistance": 100,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 0,
    "OtherProjects": 4,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Louisiana",
    "Index": 18,
    "Lat": 30.39183,
    "Long": -92.329102,
    "ProjectTotal": 8,
    "BridgeDeckArea": 1774652,
    "PavementDistance": 484,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 6,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Maine",
    "Index": 19,
    "Lat": 45.367584,
    "Long": -68.972168,
    "ProjectTotal": 30,
    "BridgeDeckArea": 1551444,
    "PavementDistance": 284,
    "PavementStructureEvaluation": 8,
    "BridgeDeckScanning": 20,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 2,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Maryland",
    "Index": 20,
    "Lat": 39.045753,
    "Long": -76.641273,
    "ProjectTotal": 16,
    "BridgeDeckArea": 967626,
    "PavementDistance": 380,
    "PavementStructureEvaluation": 6,
    "BridgeDeckScanning": 4,
    "OtherProjects": 4,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 2
  },
  {
    "State": "Massachusetts",
    "Index": 21,
    "Lat": 42.407211,
    "Long": -71.382439,
    "ProjectTotal": 108,
    "BridgeDeckArea": 1212482,
    "PavementDistance": 52,
    "PavementStructureEvaluation": 6,
    "BridgeDeckScanning": 30,
    "OtherProjects": 38,
    "ConcreteStructureScanning": 18,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 16
  },
  {
    "State": "Michigan",
    "Index": 22,
    "Lat": 44.182205,
    "Long": -84.506836,
    "ProjectTotal": 16,
    "BridgeDeckArea": 7228330,
    "PavementDistance": 244,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 8,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 4,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Minnesota",
    "Index": 23,
    "Lat": 46.39241,
    "Long": -94.63623,
    "ProjectTotal": 56,
    "BridgeDeckArea": 8225162,
    "PavementDistance": 4578,
    "PavementStructureEvaluation": 36,
    "BridgeDeckScanning": 18,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 2,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Mississippi",
    "Index": 24,
    "Lat": 33,
    "Long": -90,
    "ProjectTotal": 1,
    "BridgeDeckArea": 0,
    "PavementDistance": 344,
    "PavementStructureEvaluation": 1,
    "BridgeDeckScanning": 0,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Missouri",
    "Index": 25,
    "Lat": 38.573936,
    "Long": -92.60376,
    "ProjectTotal": 10,
    "BridgeDeckArea": 1581172,
    "PavementDistance": 0,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 8,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Montana",
    "Index": 26,
    "Lat": 46.96526,
    "Long": -109.53369,
    "ProjectTotal": 8,
    "BridgeDeckArea": 4635798,
    "PavementDistance": 50,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 6,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Nebraska",
    "Index": 27,
    "Lat": 41.5,
    "Long": -100,
    "ProjectTotal": 6,
    "BridgeDeckArea": 271942,
    "PavementDistance": 0,
    "PavementStructureEvaluation": 0,
    "BridgeDeckScanning": 4,
    "OtherProjects": 2,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Nevada",
    "Index": 28,
    "Lat": 39.876019,
    "Long": -117.22412,
    "ProjectTotal": 6,
    "BridgeDeckArea": 4960884,
    "PavementDistance": 24,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "New Hampshire",
    "Index": 29,
    "Lat": 44,
    "Long": -71.5,
    "ProjectTotal": 20,
    "BridgeDeckArea": 952972,
    "PavementDistance": 362,
    "PavementStructureEvaluation": 6,
    "BridgeDeckScanning": 12,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 2
  },
  {
    "State": "New Jersey",
    "Index": 30,
    "Lat": 39.833851,
    "Long": -74.871826,
    "ProjectTotal": 4,
    "BridgeDeckArea": 1320,
    "PavementDistance": 1206,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "New Mexico",
    "Index": 31,
    "Lat": 34.307144,
    "Long": -106.01807,
    "ProjectTotal": 1,
    "BridgeDeckArea": 0,
    "PavementDistance": 2,
    "PavementStructureEvaluation": 1,
    "BridgeDeckScanning": 0,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "New York",
    "Index": 32,
    "Lat": 43,
    "Long": -75,
    "ProjectTotal": 76,
    "BridgeDeckArea": 10360008,
    "PavementDistance": 294,
    "PavementStructureEvaluation": 10,
    "BridgeDeckScanning": 58,
    "OtherProjects": 2,
    "ConcreteStructureScanning": 6,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "North Carolina",
    "Index": 33,
    "Lat": 35.782169,
    "Long": -80.793457,
    "ProjectTotal": 10,
    "BridgeDeckArea": 175856,
    "PavementDistance": 72,
    "PavementStructureEvaluation": 6,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "North Dakota",
    "Index": 34,
    "Lat": 47.650589,
    "Long": -100.43701,
    "ProjectTotal": 20,
    "BridgeDeckArea": 679032,
    "PavementDistance": 8648,
    "PavementStructureEvaluation": 10,
    "BridgeDeckScanning": 6,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 2,
    "SubsurfaceUtilityEngineering": 2
  },
  {
    "State": "Ohio",
    "Index": 35,
    "Lat": 40.367474,
    "Long": -82.996216,
    "ProjectTotal": 30,
    "BridgeDeckArea": 2902426,
    "PavementDistance": 214,
    "PavementStructureEvaluation": 8,
    "BridgeDeckScanning": 22,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Oklahoma",
    "Index": 36,
    "Lat": 36.084621,
    "Long": -96.921387,
    "ProjectTotal": 6,
    "BridgeDeckArea": 0,
    "PavementDistance": 7360,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Oregon",
    "Index": 37,
    "Lat": 44,
    "Long": -120.5,
    "ProjectTotal": 10,
    "BridgeDeckArea": 5948624,
    "PavementDistance": 232,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 6,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Pennsylvania",
    "Index": 38,
    "Lat": 41.203323,
    "Long": -77.194527,
    "ProjectTotal": 36,
    "BridgeDeckArea": 2571860,
    "PavementDistance": 476,
    "PavementStructureEvaluation": 8,
    "BridgeDeckScanning": 26,
    "OtherProjects": 2,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Rhode Island",
    "Index": 39,
    "Lat": 41.742325,
    "Long": -71.742332,
    "ProjectTotal": 26,
    "BridgeDeckArea": 6891986,
    "PavementDistance": 22,
    "PavementStructureEvaluation": 10,
    "BridgeDeckScanning": 16,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "South Carolina",
    "Index": 40,
    "Lat": 33.836082,
    "Long": -81.163727,
    "ProjectTotal": 24,
    "BridgeDeckArea": 154888,
    "PavementDistance": 826,
    "PavementStructureEvaluation": 18,
    "BridgeDeckScanning": 6,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "South Dakota",
    "Index": 41,
    "Lat": 44.5,
    "Long": -100,
    "ProjectTotal": 6,
    "BridgeDeckArea": 163674,
    "PavementDistance": 48,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Tennessee",
    "Index": 42,
    "Lat": 35.860119,
    "Long": -86.660156,
    "ProjectTotal": 10,
    "BridgeDeckArea": 941372,
    "PavementDistance": 5774,
    "PavementStructureEvaluation": 6,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Texas",
    "Index": 43,
    "Lat": 31,
    "Long": -100,
    "ProjectTotal": 8,
    "BridgeDeckArea": 294146,
    "PavementDistance": 276,
    "PavementStructureEvaluation": 4,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 2,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Utah",
    "Index": 44,
    "Lat": 39.41922,
    "Long": -111.95068,
    "ProjectTotal": 10,
    "BridgeDeckArea": 321920,
    "PavementDistance": 3962,
    "PavementStructureEvaluation": 8,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Vermont",
    "Index": 45,
    "Lat": 44,
    "Long": -72.699997,
    "ProjectTotal": 6,
    "BridgeDeckArea": 0,
    "PavementDistance": 186,
    "PavementStructureEvaluation": 6,
    "BridgeDeckScanning": 0,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Virginia",
    "Index": 46,
    "Lat": 37.926868,
    "Long": -78.024902,
    "ProjectTotal": 112,
    "BridgeDeckArea": 5408600,
    "PavementDistance": 7692,
    "PavementStructureEvaluation": 64,
    "BridgeDeckScanning": 32,
    "OtherProjects": 6,
    "ConcreteStructureScanning": 10,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Washington",
    "Index": 47,
    "Lat": 47.751076,
    "Long": -120.74014,
    "ProjectTotal": 2,
    "BridgeDeckArea": 44160,
    "PavementDistance": 0,
    "PavementStructureEvaluation": 0,
    "BridgeDeckScanning": 2,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "West Virginia",
    "Index": 48,
    "Lat": 39,
    "Long": -80.5,
    "ProjectTotal": 0,
    "BridgeDeckArea": 0,
    "PavementDistance": 0,
    "PavementStructureEvaluation": 0,
    "BridgeDeckScanning": 0,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Wisconsin",
    "Index": 49,
    "Lat": 44.5,
    "Long": -89.5,
    "ProjectTotal": 118,
    "BridgeDeckArea": 65958038,
    "PavementDistance": 244,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 112,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 4,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Wyoming",
    "Index": 50,
    "Lat": 43.07597,
    "Long": -107.29028,
    "ProjectTotal": 6,
    "BridgeDeckArea": 568438,
    "PavementDistance": 70,
    "PavementStructureEvaluation": 2,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "Puerto Rico",
    "Index": 51,
    "Lat": 18.2,
    "Long": -66.66,
    "ProjectTotal": 0,
    "BridgeDeckArea": 0,
    "PavementDistance": 0,
    "PavementStructureEvaluation": 0,
    "BridgeDeckScanning": 0,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "District of Columbia",
    "Index": 52,
    "Lat": 38.898,
    "Long": -77.04,
    "ProjectTotal": 4,
    "BridgeDeckArea": 439662,
    "PavementDistance": 0,
    "PavementStructureEvaluation": 0,
    "BridgeDeckScanning": 4,
    "OtherProjects": 0,
    "ConcreteStructureScanning": 0,
    "ConsultingResearch": 0,
    "SubsurfaceUtilityEngineering": 0
  },
  {
    "State": "International Projects",
    "Index": 53,
    "Lat": 34.599507,
    "Long": -67.090337,
    "ProjectTotal": 13,
    "BridgeDeckArea": 31835,
    "PavementDistance": 1297,
    "PavementStructureEvaluation": 7,
    "BridgeDeckScanning": 1,
    "OtherProjects": 3,
    "ConcreteStructureScanning": 1,
    "ConsultingResearch": 1,
    "SubsurfaceUtilityEngineering": 0
  }
 ]